spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=3822
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

token.signing.key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

jwt.secret=MyVerySecretKeyForJWT12345
jwt.expiration=3600000

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html
spring.web.resources.add-mappings=true
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
server.ssl.enabled=false
spring.mvc.log-request-details=true

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.kafka.bootstrap-servers=localhost:29092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.acks=1
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.consumer.group-id=order-1
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

topic.add-order=add-order-event
topic.send-order=send-order-event