spring.application.name=order-service
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=3822
spring.datasource.driver-class-name=org.postgresql.Driver