spring.application.name=NotificationService

spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=3822
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8082

spring.kafka.bootstrap-servers=localhost:29092

spring.kafka.consumer.group-id=order-1
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=backend.megamarket.NotificationService.Service.messaging.OrderEventListDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
topic.send-order=send-order-event

token.signing.key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
jwt.secret=MyVerySecretKeyForJWT12345
jwt.expiration=3600000