syntax = "proto3";

package inventory;

option java_multiple_files = true;
option java_package = "client.inventory_service.response.grpc";

message ProductQueryDto {
  int64 productId = 1;
  int64 quantity = 2;
}

enum ProductStatus {
  OK = 0;
  INSUFFICIENT_QUANTITY = 1;
}

message ProductInfoDto {
  int64 productId = 1;
  string name = 2;
  double price = 3;
  double discount = 4;
  int64 availableQuantity = 5;
  ProductStatus status = 6;
}

message InventoryRequestDto {
  int64 orderId = 1;
  repeated ProductQueryDto products = 2;
}

message InventoryResponseDto {
  int64 orderId = 1;
  repeated ProductInfoDto items = 2;
}

service InventoryService {
  rpc checkInventory(InventoryRequestDto) returns (InventoryResponseDto);
  rpc addOrder(InventoryRequestDto) returns (InventoryResponseDto);
}
